//
//  IntroTextView.swift
//  WWDC
//
//  Created by Lucca Rocha on 13/04/23.
//

import SwiftUI

struct IntroTextView: View {
    @Binding var GameStarted: Bool
    var TextArray: [String] = [
        "Welcome, brave adventurer, to \"Resource Rush\" the ultimate mission to save our beloved planet Earth from the brink of destruction. As an astronaut, you have been chosen to lead this crucial mission, where you will have to navigate through various challenges to harness Earth's resources and use them in the most efficient way possible.",
        "The Earth is facing a crisis due to overexploitation of its resources and climate change, and we need your help to restore its balance. Your task is to find innovative solutions and smartly utilize Earth's resources to mitigate the damages already caused and prevent further harm.",
        "",
        "",
        "Remember, every decision you make will have an impact on the Earth's health and survival. So, choose wisely, and let's work together to save our beautiful planet from destruction. Are you ready for this challenging yet rewarding adventure? Let's begin!",
        "Gameplay Tip: Drag and drop the resources from the bottom left"
    ]
    @Binding var index: Int
    var body: some View {
        ZStack {
            if TextArray[index] != "" {
                Text(TextArray[index])
                    .foregroundColor(.white)
                    .font(.largeTitle)
                    .frame(width: UIScreen.main.bounds.width * 0.8)
                    .lineSpacing(1.5)
                    .padding(.bottom, 40)
                    .padding(.trailing, 100)
                //.fontWeight(.light)
            }
            else if index == 2{
                VStack(spacing: 40){
                    ExplainView(imagename: "Co2Explain", description: "CO2 capture is a new technology that removes carbon dioxide emissions from industrial processes and power plants. The captured CO2 is stored underground in geological formations.")
                    
                    ExplainView(imagename: "SunExplain", description: "Solar panels turn sunlight into electricity. They're eco-friendly and need lots of sun to work well.")
                }
            }
            else if index == 3{
                VStack(spacing: 40){
                    ExplainView(imagename: "WaterExplain", description: "Water is used in industries for cooling, heating, cleaning, and as a solvent in chemical reactions. It is also used in the production of various products and for irrigation and mineral extraction in some industries.")
                    ExplainView(imagename: "WindExplain", description: "Wind energy is generated by wind turbines that use the wind to turn blades, which then turn a rotor connected to a generator that produces electricity. It's a renewable and clean source of energy.")
                }
            }
            
        }
        .frame(width: UIScreen.main.bounds.width, height: UIScreen.main.bounds.height)
        .background{
            //por algum motivo precisa disso sla pq
            Color.white.opacity(0.0001)
        }
        .onTapGesture {
            if (index < (TextArray.count) - 1){
                print(index)
                index += 1
            }
            else{
                GameStarted.toggle()
            }
            
        }
    }
}
struct ExplainView: View{
    var imagename: String
    var description: String = "lorem ipsum"
    var body: some View{
        Image(imagename)
            .resizable()
            .scaledToFit()
            .frame(height: 210)
            .offset(x: -30)
            .overlay {
                Text(description)
                    .bold()
                    .font(.title2)
                    .foregroundColor(.white)
                    .frame(width: UIScreen.main.bounds.width * 0.38, height: 180)
                    .multilineTextAlignment(.leading)
                    .padding(.trailing,40)
            }
    }
}

struct IntroTextView_Previews: PreviewProvider {
    static var previews: some View {
        ExplainView(imagename: "WaterExplain", description: "Solar panels turn sunlight into electricity. They're eco-friendly and need lots of sun to work well.")
            .previewInterfaceOrientation(.landscapeLeft)

    }
}
